/*
 * Copyright 2026 Alexander Sommer, Samuel Skovbakke
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase.typer

import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.ast.shared.EffSymOrRigidVar.{Eff, RigidVar}
import ca.uwaterloo.flix.language.ast.shared.{EffSymOrRigidVar, RegionScope}
import ca.uwaterloo.flix.language.ast.{RigidityEnv, SourceLocation, Type, TypeConstructor}
import ca.uwaterloo.flix.language.errors.TypeError
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint.{EffConflicted, Provenance}
import ca.uwaterloo.flix.language.phase.unification.shared.{BoolAlg, BoolUnificationException, CofiniteIntSet, SveAlgorithm}
import ca.uwaterloo.flix.language.phase.unification.zhegalkin.{ZhegalkinAlgebra, ZhegalkinExpr}
import org.apache.commons.lang3.mutable.Mutable

import scala.annotation.tailrec

/** Analyzes constraints generated by ConstraintSolver in order to provide code
  * actions, inlay hints and better error messages.
  *
  * This module constructs a directed graph representing effect flow from type
  * constraints and performs breadth-first search to identify specific paths
  * from effect to another effect. This helps generate specific errors that help
  * with diagnosing effect related errors. It generates lists of all paths from
  * some effect flowing into another (conflicting) effect.
  */
object EffectProvenance {

  case class Env(unvisited: List[Type], locs: List[(SourceLocation, SourceLocation, SourceLocation)], sourceEffect: EffSymOrRigidVar) {


    def addLoc(typeConstraint: TypeConstraint): Env = typeConstraint match {
      case TypeConstraint.Equality(tpe1, tpe2, prov) => this.copy(locs = (tpe1.loc, tpe2.loc, prov.loc) :: locs)
      case _ => this
    }

    def popUnvisited: Env = unvisited match {
      case Nil => this
      case _ :: xs => this.copy(unvisited = xs)
    }


    def addUnvisited(constraint: TypeConstraint)(implicit renv: RigidityEnv, scope: RegionScope): Env = constraint match {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def deconstruct(t: Type, env: Env): Env = t match {
          case Type.Var(sym, _) =>
            if (!env.unvisited.contains(t) && renv.isFlexible(sym)) env.copy(unvisited = t :: env.unvisited) else env
          case Type.Apply(lt, rt, _) => deconstruct(rt, deconstruct(lt, env))
          case _ => env
        }

        val e1 = deconstruct(tpe1, this)
        deconstruct(tpe2, e1)
      case _ => this
    }

  }

  private def emptyEnvWithSource(source: TypeConstraint): Option[Env] = source match {
    case TypeConstraint.Equality(_, _, prov) => prov match {
      case Provenance.Source(_, eff2, _) => typeToSym(eff2).map(Env(List.empty, List.empty, _))
      case _ => None
    }
    case _ => None
  }

  /** Builds an effect conflict graph from given constraints. Then analyzes the
    * effect conflict graph and returns a list of effect conflicts.
    *
    * Returns a list of effect conflicts if any are found, or None if no good
    * effect error could be made. A conflict is: a path from an effect to a
    * differing effect. E.g. IO -> ... -> {}. This is the main entry point for
    * effect provenance analysis.
    *
    * @param constrs0
    * the list of type constraints to analyze
    * @return
    * a list of conflicts if conflicts could be found, None otherwise
    */
  def getErrors(constrs0: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv): Option[List[EffConflicted]] = {
    implicit val alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]] = new ZhegalkinAlgebra[CofiniteIntSet](CofiniteIntSet.LatticeOps)
    if (isDebug(constrs0)) return None
    val sovser = constrs0.filter {
      case TypeConstraint.Equality(_, _, prov) => prov match {
        case Provenance.Source(_, _, _) => true
        case _ => false
      }
      case _ => false
    }
    val res = sovser.flatMap(a => emptyEnvWithSource(a).flatMap(doStuff(List(a), List.empty, constrs0, _)))
    if (res.isEmpty) None else Some(res)
  }

  private def doStuff(workList: List[TypeConstraint], unifiables: List[(ZhegalkinExpr[CofiniteIntSet], ZhegalkinExpr[CofiniteIntSet])], constr0: List[TypeConstraint], env: Env)(implicit renv: RigidityEnv, scope: RegionScope, alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]]): Option[EffConflicted] = {
    val env1 = env.popUnvisited
    val a = workList.flatMap(constraintToZhegalkin)
    try {
      SveAlgorithm.sveAll(a)
      val env2 = workList.foldLeft(env1)((acc, x) => acc.addUnvisited(x).addLoc(x))
      val b = env2.unvisited.flatMap(findType(_, constr0))
      val newWorkList = b.foldLeft(workList)((acc, x) => if (acc.contains(x)) acc else x :: acc)
      doStuff(newWorkList, a ::: unifiables, constr0, env2)
    } catch {
      case _: BoolUnificationException =>
        println("Success!")
        println(workList)
        mkError(workList.head, env.addLoc(workList.head))
    }
  }


  private def findType(tpe: Type, constr0: List[TypeConstraint]): List[TypeConstraint] = {
    constr0.filter {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isTpe(t: Type): Boolean = t match {
          case Type.Apply(lt, rt, _) => isTpe(lt) || isTpe(rt)
          case _ => t == tpe
        }

        isTpe(tpe1) || isTpe(tpe2)
      case _ => false
    }
  }


  private def constraintToZhegalkin(constr: TypeConstraint)(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]]): Option[(ZhegalkinExpr[CofiniteIntSet], ZhegalkinExpr[CofiniteIntSet])] = constr match {
    case TypeConstraint.Equality(tpe1, tpe2, _) =>
      (typeToZhegalkin(tpe1), typeToZhegalkin(tpe2)) match {
        case (Some(x), Some(y)) => Some((x, y))
        case _ => None
      }
    case _ => None
  }

  private def mkError(breakPoint: TypeConstraint, env: Env): Option[EffConflicted] = breakPoint match {
    case TypeConstraint.Equality(_, _, prov) => prov match {
      case Provenance.ExpectEffect(expected, _, _) => expected match {
        case Type.Cst(tc, _) => tc match {
          case TypeConstructor.Pure =>
            val isIO = env.sourceEffect match {
              case Eff(symbol) => symbol match {
                case Symbol.IO => true
                case _ => false
              }
              case RigidVar(_) => false
            }
            val explicitImplicit: TypeError = (env.locs.head._1.isReal, isIO) match {
              case (true, true) => TypeError.ExplicitlyPureFunctionUsesIO(env.locs.head._1, env.locs.last._3)
              case (true, false) => TypeError.ExplicitlyPureFunctionUsesEffect(env.sourceEffect, env.locs.head._1, env.locs.last._3)
              case (false, true) => TypeError.ImplicitlyPureFunctionUsesIO(env.locs.head._3, env.locs.last._3)
              case (false, false) => TypeError.ImplicitlyPureFunctionUsesEffect(env.sourceEffect, env.locs.head._3, env.locs.last._3)
            }
            Some(EffConflicted(explicitImplicit))

          case TypeConstructor.Effect(_, _) => None
          case _ => None
        }
        case _ => None
      }
      case _ => None
    }
    case _ => None
  }

  private def isDebug(constrs: List[TypeConstraint]): Boolean = {
    constrs.exists {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        val isDb = (t: Type) => t match {
          case Type.Cst(tc, _) => tc match {
            case TypeConstructor.Effect(sym, _) => sym match {
              case Symbol.Debug => true
              case _ => false
            }
            case _ => false
          }
          case _ => false
        }
        isDb(tpe1) || isDb(tpe2)
      case _ => false
    }
  }


  private def typeToZhegalkin(tpe: Type)(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]]): Option[ZhegalkinExpr[CofiniteIntSet]] = {
    tpe match {
      case Type.Var(sym, _) => Some(alg.mkVar(sym.id))
      case Type.Cst(tc, _) => Some(alg.mkCst(tc.hashCode()))
      case Type.Apply(lt, rt, _) => (typeToZhegalkin(lt), typeToZhegalkin(rt)) match {
        // Everything is Union :)
        case (Some(x), Some(y)) => Some(alg.mkAnd(x, y))
        case (Some(x), None) => Some(x)
        case (None, Some(y)) => Some(y)
        case (None, None) => None
      }
      case _ => None
    }
  }

  private def typeToSym(tpe: Type): Option[EffSymOrRigidVar] = tpe match {
    case Type.Var(sym, _) => Some(RigidVar(sym))
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => Some(Eff(Symbol.mkEffSym("Pure")))
      case TypeConstructor.Effect(sym, _) => Some(Eff(sym))
      case _ => None
    }
    case _ => None
  }
}

