/*
 * Copyright 2026 Alexander Sommer, Samuel Skovbakke
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase.typer

import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.ast.shared.EffSymOrRigidVar.{Eff, RigidVar}
import ca.uwaterloo.flix.language.ast.shared.{EffSymOrRigidVar, RegionScope}
import ca.uwaterloo.flix.language.ast.{RigidityEnv, SourceLocation, Type, TypeConstructor}
import ca.uwaterloo.flix.language.errors.TypeError
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint.{EffConflicted, Provenance}
import ca.uwaterloo.flix.language.phase.unification.shared.{BoolAlg, BoolSubstitution, BoolUnificationException, CofiniteIntSet, SveAlgorithm}
import ca.uwaterloo.flix.language.phase.unification.zhegalkin.{ZhegalkinAlgebra, ZhegalkinExpr}
import org.apache.commons.lang3.mutable.Mutable

import scala.annotation.tailrec
import scala.collection.immutable.Queue

/** Analyzes constraints generated by ConstraintSolver in order to provide code
  * actions, inlay hints and better error messages.
  *
  * This module constructs a directed graph representing effect flow from type
  * constraints and performs breadth-first search to identify specific paths
  * from effect to another effect. This helps generate specific errors that help
  * with diagnosing effect related errors. It generates lists of all paths from
  * some effect flowing into another (conflicting) effect.
  */
object EffectProvenance {


  /** Builds an effect conflict graph from given constraints. Then analyzes the
    * effect conflict graph and returns a list of effect conflicts.
    *
    * Returns a list of effect conflicts if any are found, or None if no good
    * effect error could be made. A conflict is: a path from an effect to a
    * differing effect. E.g. IO -> ... -> {}. This is the main entry point for
    * effect provenance analysis.
    *
    * @param constrs0
    * the list of type constraints to analyze
    * @return
    * a list of conflicts if conflicts could be found, None otherwise
    */
  def getErrors(constrs0: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv): Option[List[EffConflicted]] = {
    implicit val alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]] = new ZhegalkinAlgebra[CofiniteIntSet](CofiniteIntSet.LatticeOps)
    if (isDebug(constrs0)) return None
    val (sources, rest) = constrs0.partition {
      case TypeConstraint.Equality(_, _, prov) => prov match {
        case Provenance.Source(_, _, _) => true
        case _ => false
      }
      case _ => false
    }
    val res = sources.map(a => (a, initialSub(a, Map.empty))
    ).flatMap {
      case (c, (Some(ze), m)) => doStuff(c, rest, ze, m)
      case _ => None
    }
    if (res.isEmpty) None else Some(res)
  }

  private def doStuff(initial: TypeConstraint, constrs0: List[TypeConstraint], initialSub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): Option[EffConflicted] = {
    @tailrec
    def doStuffHelper(prev: TypeConstraint, unvisited: List[TypeConstraint], workQueue: Queue[TypeConstraint], sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], m: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): Option[EffConflicted] = {
      val (workQueue2, unvisited2) = findNext(prev, unvisited, workQueue)
      println(workQueue2)
      val (x, q) = workQueue2.dequeue
      val (newSub, newMap) = applySubs(x, sub, m)
      newSub match {
        case Some(ns) => doStuffHelper(x, unvisited2, q, ns, newMap)
        case None => mkError(initial, x)
      }
    }

    doStuffHelper(initial, constrs0, Queue.empty, initialSub, idMap)
  }

  private def mkError(source: TypeConstraint, sink: TypeConstraint): Option[EffConflicted] = {
    val a = source match {
      case TypeConstraint.Equality(_, _, prov) => prov match {
        case Provenance.Source(_, eff2, _) => Some(eff2)
        case _ => None
      }
      case _ => None
    }
    a.flatMap(sourceTpe => {

      val sourceSyms = typeToSym(sourceTpe)
      sink match {
        case TypeConstraint.Equality(_, _, prov) => prov match {
          case Provenance.ExpectEffect(expected, _, _) => expected match {
            case Type.Cst(tc, loc) => tc match {
              case TypeConstructor.Pure =>
                val isIO = sourceSyms match {
                  case Eff(symbol) :: Nil => symbol == Symbol.IO
                  case _ => false
                }
                val err: TypeError = (loc.isReal, isIO) match {
                  case (true, true) => TypeError.ExplicitlyPureFunctionUsesIO(loc, source.loc)
                  case (true, false) => TypeError.ExplicitlyPureFunctionUsesEffect(sourceSyms.head, loc, source.loc)
                  case (false, true) => TypeError.ImplicitlyPureFunctionUsesIO(prov.loc, source.loc)
                  case (false, false) => TypeError.ImplicitlyPureFunctionUsesEffect(sourceSyms.head, prov.loc, source.loc)
                }
                Some(EffConflicted(err))
              case _ => None
            }
            case _ => None
          }
          case _ => None
        }
        case _ => None
    }})
  }

  private def applySubs(current: TypeConstraint, sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]]], Map[Type, Int]) = {
    constraintToZhegalkin(current, idMap) match {
      case (Some((x, y)), nm) =>
        val sx = sub.apply(x)
        val sy = sub.apply(y)
        try {
          val newSub = SveAlgorithm.sveAll(List((sx, sy)))
          (Some(sub ++ newSub), nm)
        } catch {
          case _: BoolUnificationException => (None, nm)
        }
      case (_, nm) => (None, nm)
    }
  }

  private def initialSub(source: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]]], Map[Type, Int]) = {
    constraintToZhegalkin(source, idMap) match {
      case (Some((x, y)), nm) =>
        try {
          (Some(SveAlgorithm.sveAll(List((x, y)))), nm)
        } catch {
          case _: BoolUnificationException => (None, nm)
        }
      case (_, nm) => (None, nm)
    }
  }

  private def findNext(prev: TypeConstraint, constrs0: List[TypeConstraint], workQueue: Queue[TypeConstraint]): (Queue[TypeConstraint], List[TypeConstraint]) = {
    prev match {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        val x = findType(tpe1, constrs0)
        val y = findType(tpe2, constrs0)
        ((x ++ y).foldLeft(workQueue)((acc, x) => acc.enqueue(x)), constrs0.diff(x ++ y))
      case _ => (workQueue, constrs0)
    }
  }


  private def findType(tpe: Type, constr0: List[TypeConstraint]): List[TypeConstraint] = {
    constr0.filter {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isTpe(t: Type): Boolean = t match {
          case Type.Apply(lt, rt, _) => isTpe(lt) || isTpe(rt)
          case _ => t == tpe
        }

        isTpe(tpe1) || isTpe(tpe2)
      case _ => false
    }
  }


  private def constraintToZhegalkin(constr: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[(ZhegalkinExpr[CofiniteIntSet], ZhegalkinExpr[CofiniteIntSet])], Map[Type, Int]) = constr match {
    case TypeConstraint.Equality(tpe1, tpe2, _) =>
      typeToZhegalkin(tpe1, idMap) match {
        case (None, nm) => (None, nm)
        case (Some(xh1), nm) => typeToZhegalkin(tpe2, nm) match {
          case (Some(xh2), nnm) => (Some((xh1, xh2)), nnm)
          case (None, nnm) => (None, nnm)
        }
      }
    case _ => (None, idMap)
  }


  private def isDebug(constrs: List[TypeConstraint]): Boolean = {
    constrs.exists {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isDb(t: Type): Boolean = t match {
          case Type.Cst(tc, _) => tc match {
            case TypeConstructor.Effect(sym, _) => sym match {
              case Symbol.Debug => true
              case _ => false
            }
            case _ => false
          }
          case Type.Apply(tl, tr, _) => isDb(tl) || isDb(tr)
          case _ => false
        }
        isDb(tpe1) || isDb(tpe2)
      case _ => false
    }
  }


  /**
    * convert a Type into a Zhegalkin expression and update the idMap if necessary
    * @param tpe Type to convert
    * @param idMap map containing ids of converted types
    * @return a tuple of Option[ZhegalkinExpr] and idMap, so an idMap is always returned
    */
  private def typeToZhegalkin(tpe: Type, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[ZhegalkinExpr[CofiniteIntSet]], Map[Type, Int]) = {
    val a = (default: Int, z: Int => ZhegalkinExpr[CofiniteIntSet]) => {
      val id = idMap.getOrElse(tpe, default)
      (Some(z(id)), idMap + (tpe -> id))
    }
    val varId = idMap.values.minOption.getOrElse(0).min(0) - 1
    val cstId = idMap.values.maxOption.getOrElse(0).max(0) + 1
    tpe match {
      case Type.Var(sym, _) =>
        if (renv.isFlexible(sym)) {
          a(varId, alg.mkVar)
        }
        else {
          a(cstId, alg.mkCst)
        }
      case Type.Cst(_, _) => a(cstId, alg.mkCst)
      case Type.Apply(tl, tr, _) => tpe.baseType match {
        case Type.Cst(tc, _) => tc match {
          case TypeConstructor.Union => typeToZhegalkin(tl, idMap) match {
            case (Some(zhL), nm) => typeToZhegalkin(tr, nm) match {
              case (Some(zhR), nnm) => (Some(alg.mkOr(zhL, zhR)), nnm)
              case (None, nnm) => (None, nnm)
            }
            case (None, nm) => (None, nm)
          }
          case _ => (None, idMap)
        }
        case _ => (None, idMap)
      }
      case _ => (None, idMap)
    }
  }


  private def typeToSym(tpe: Type): List[EffSymOrRigidVar] = tpe match {
    case Type.Var(sym, _) => List(RigidVar(sym))
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => List(Eff(Symbol.mkEffSym("Pure")))
      case TypeConstructor.Effect(sym, _) => List(Eff(sym))
      case _ => Nil
    }
    case Type.Apply(tl, tr, _) => typeToSym(tl) ++ typeToSym(tr)
    case _ => Nil
  }
}

