/*
 * Copyright 2026 Alexander Sommer, Samuel Skovbakke
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase.typer

import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.ast.shared.EffSymOrRigidVar.{Eff, RigidVar}
import ca.uwaterloo.flix.language.ast.shared.{EffSymOrRigidVar, RegionScope}
import ca.uwaterloo.flix.language.ast.{RigidityEnv, SourceLocation, Type, TypeConstructor}
import ca.uwaterloo.flix.language.errors.TypeError
import ca.uwaterloo.flix.language.phase.typer.TypeConstraint.{EffConflicted, Provenance}
import ca.uwaterloo.flix.language.phase.unification.shared.{BoolAlg, BoolSubstitution, BoolUnificationException, CofiniteIntSet, SveAlgorithm}
import ca.uwaterloo.flix.language.phase.unification.zhegalkin.{ZhegalkinAlgebra, ZhegalkinExpr}
import org.apache.commons.lang3.mutable.Mutable

import java.util.NoSuchElementException
import scala.annotation.tailrec
import scala.collection.immutable.Queue

/** Analyzes constraints generated by ConstraintSolver in order to provide code
  * actions, inlay hints and better error messages.
  *
  * This module constructs a directed graph representing effect flow from type
  * constraints and performs breadth-first search to identify specific paths
  * from effect to another effect. This helps generate specific errors that help
  * with diagnosing effect related errors. It generates lists of all paths from
  * some effect flowing into another (conflicting) effect.
  */
object EffectProvenance {


  /** Builds an effect conflict graph from given constraints. Then analyzes the
    * effect conflict graph and returns a list of effect conflicts.
    *
    * Returns a list of effect conflicts if any are found, or None if no good
    * effect error could be made. A conflict is: a path from an effect to a
    * differing effect. E.g. IO -> ... -> {}. This is the main entry point for
    * effect provenance analysis.
    *
    * @param constrs0
    * the list of type constraints to analyze
    * @return
    * a list of conflicts if conflicts could be found, None otherwise
    */
  def getErrors(constrs0: List[TypeConstraint])(implicit scope: RegionScope, renv: RigidityEnv): Option[List[EffConflicted]] = {
    implicit val alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]] = new ZhegalkinAlgebra[CofiniteIntSet](CofiniteIntSet.LatticeOps)
    if (isDebug(constrs0)) return None
    val (sources, rest) = constrs0.partition {
      case TypeConstraint.Equality(_, _, prov) => prov match {
        case Provenance.Source(_, eff2, _) => !isFlexible(eff2) && !isPure(eff2)
        case Provenance.ExpectType(_, _, _) => true
        case _ => false
      }
      case _ => false
    }
    var s = rest.foldLeft(Set.empty[Type]) {
      case (acc, TypeConstraint.Equality(_, _, prov)) => prov match {
        case Provenance.ExpectType(expected, _, _) => if (!isPure(expected)) acc ++ consTypeArgs(expected) else acc
        case Provenance.ExpectEffect(expected, _, _) => if (!isPure(expected)) acc ++ consTypeArgs(expected) else acc
        case _ => acc
      }
      case (acc, _) => acc
    }
    val handledEffs = constrs0.foldLeft(Set.empty[Type])((acc, x) => findHandled(x) ++ acc)
    val res = sources.map(a => (a, initialSub(a, Map.empty))
    ).flatMap {
      case (c, (Left(ze), m)) =>
        val (errs, unused) = doStuff(c, rest, ze, m, s, handledEffs)
        s = unused
        errs
      case (_, (Right(err), _)) => err
      case _ => None
    }
    // test if all constraints are be solved by themselves
    val singles = constrs0.filterNot(pureSource).flatMap(initialSub(_, Map.empty) match {
      case (Right(effErr), _) => Some(effErr)
      case (Left(_), _) => None
    }).flatten
    val unused = s.map(x => EffConflicted(TypeError.UnusedEffectInSignature(typeToSym(x).head, x.loc))).toList
    val r = unused ++ res ++ singles
    if (r.isEmpty) None else Some(r)
  }

  private def isPure(tpe: Type): Boolean = tpe match {
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => true
      case _ => false
    }
    case _ => false
  }

  private def isSink(constr: TypeConstraint): Boolean = constr match {
    case TypeConstraint.Equality(_, _, prov) => prov match {
      case Provenance.ExpectEffect(_, _, _) => true
      case _ => false
    }
    case _ => false
  }


  private def doStuff(initial: TypeConstraint, constrs0: List[TypeConstraint], initialSub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int], unused: Set[Type], handledEffs: Set[Type])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (List[EffConflicted], Set[Type]) = {
    var s = unused
    s = initial match {
      case TypeConstraint.Equality(_, tpe2, _) =>
        s.diff(consTypeArgs(tpe2).toSet)
      case _ => s
    }

    def doStuffHelper(visited: List[TypeConstraint], unvisited: List[TypeConstraint], workQueue: Queue[TypeConstraint], sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], m: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): List[EffConflicted] = {
      val (workQueue2, unvisited2) = findNext(visited, unvisited, workQueue, idMap)
      try {
        val (x, q) = workQueue2.dequeue
        val (newSub, newMap) = applySubs(x, sub, m)
        newSub match {
          case Some(ns) =>
            if (isSink(visited.head)) Nil else doStuffHelper(x :: visited, unvisited2, q, ns, newMap)
          case None =>
            println("success")
            val (errs, nu) = mkErrors(initial, x, s, handledEffs)
            s = nu
            errs
        }
      } catch {
        case _: NoSuchElementException => println("død"); Nil
      }
    }

    (doStuffHelper(List(initial), constrs0, Queue.empty, initialSub, idMap), s)
  }

  private def mkErrors(source: TypeConstraint, sink: TypeConstraint, sinks: Set[Type], handledEffs: Set[Type]): (List[EffConflicted], Set[Type]) = {
    var s: Set[Type] = sinks
    val a = source match {
      case TypeConstraint.Equality(t1, t2, prov) => prov match {
        case Provenance.ExpectArgument(_, _, _, _, _) => Some((t2, prov))
        case Provenance.Source(_, _, _) => Some((t2, prov))
        case Provenance.ExpectType(_, _, _) => Some((t2, prov))
        case Provenance.Match(_, _, _) => Some((t2, prov))
        case Provenance.ExpectEffect(_, _, _) => Some((t1, prov))
        case _ => None
      }
      case _ => None
    }
    val b = a.map({ case (sourceTpe, sProv) =>
      println(handledEffs)
      val sourceSyms = typeToSym(sourceTpe)
      sink match {
        case TypeConstraint.Equality(tpe1, _, prov) =>
          s = s.diff(consTypeArgs(sourceTpe).toSet)
          if (tpe1 == sourceTpe) Nil else {
            val errs = prov match {
              case Provenance.ExpectEffect(expected, _, _) => expected match {
                case Type.Var(sym, _) => List(EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(RigidVar(sym)), sourceSyms.head, expected.loc, source.loc)))
                case Type.Cst(tc, loc) => tc match {
                  case TypeConstructor.Pure =>
                    val isIO = sourceSyms match {
                      case Eff(symbol) :: Nil => symbol == Symbol.IO
                      case _ => false
                    }
                    val err: TypeError = (loc.isReal, isIO) match {
                      case (true, true) => TypeError.ExplicitlyPureFunctionUsesIO(loc, source.loc)
                      case (true, false) => TypeError.ExplicitlyPureFunctionUsesEffect(sourceSyms.head, loc, source.loc)
                      case (false, true) => TypeError.ImplicitlyPureFunctionUsesIO(prov.loc, source.loc)
                      case (false, false) => TypeError.ImplicitlyPureFunctionUsesEffect(sourceSyms.head, prov.loc, source.loc)
                    }
                    List(EffConflicted(err))
                  case TypeConstructor.Effect(sym, _) => sourceTpe match {
                    case Type.Cst(tc2, _) => tc2 match {
                      case TypeConstructor.Pure => Nil
                      case _ => List(EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), sourceSyms.head, loc, source.loc)))
                    }
                    case Type.Apply(_, _, _) =>
                      consTypeArgs(sourceTpe).filterNot(x => handledEffs.contains(x) || consTypeArgs(tpe1).contains(x)).map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), typeToSym(x).head, loc, source.loc)))
                    case _ => List(EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(List(Eff(sym)), sourceSyms.head, loc, source.loc)))
                  }
                  case _ => Nil
                }
                case Type.Apply(_, _, _) =>
                  val notInDef = findDiffInTypes(sourceTpe, expected)
                  notInDef.map(x => EffConflicted(TypeError.EffectfulFunctionUsesOtherEffect(typeToSym(expected), typeToSym(x).head, expected.loc, source.loc)))
                case _ => Nil
              }
              case Provenance.ExpectArgument(expected, _, sym, _, _) => sym match {
                case ds: Symbol.DefnSym => List(EffConflicted(TypeError.ArgumentGivenWrongEffect(typeToSym(expected), sourceSyms, sink.loc, ds.loc, sProv.loc)))
                case _ => Nil
              }
              case _ => Nil
            }
            errs
          }
        case _ => Nil
      }

    }).getOrElse(Nil)
    (b, s)
  }


  private def consTypeArgs(t: Type): List[Type] = {
    val cons = (x: Type) => x :: Nil
    val concat = (x: List[Type], y: List[Type]) => x ::: y
    deconstructType(t, cons, concat, Nil)
  }

  private def findDiffInTypes(tpe1: Type, tpe2: Type): List[Type] = {
    val x = consTypeArgs(tpe1)
    val y = consTypeArgs(tpe2)
    x.diff(y)
  }

  private def applySubs(current: TypeConstraint, sub: BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]]], Map[Type, Int]) = {
    constraintToZhegalkin(current, idMap) match {
      case (Some((x, y)), nm) =>
        val sx = sub.apply(x)
        val sy = sub.apply(y)
        try {
          val newSub = SveAlgorithm.sveAll(List((sx, sy)))
          (Some(sub ++ newSub), nm)
        } catch {
          case _: BoolUnificationException => (None, nm)
        }
      case (_, nm) => (None, nm)
    }
  }

  private def initialSub(source: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Either[BoolSubstitution[ZhegalkinExpr[CofiniteIntSet]], List[EffConflicted]], Map[Type, Int]) = {
    constraintToZhegalkin(source, idMap) match {
      case (Some((x, y)), nm) =>
        try {
          (Left(SveAlgorithm.sveAll(List((x, y)))), nm)
        } catch {
          case _: BoolUnificationException => source match {
            case TypeConstraint.Equality(tpe1, tpe2, prov) =>
              val newSource = TypeConstraint.Equality(tpe2, tpe2, prov)
              val newSink = TypeConstraint.Equality(tpe1, tpe1, prov)
              (Right(mkErrors(newSource, newSink, Set.empty[Type], Set.empty)._1), nm)
            case _ => (Right(Nil), nm)
          }
        }
      case (_, nm) => (Right(Nil), nm) // Could not generate errors
    }
  }

  private def findNext(visited: List[TypeConstraint], unvisited: List[TypeConstraint], workQueue: Queue[TypeConstraint], idMap: Map[Type, Int]): (Queue[TypeConstraint], List[TypeConstraint]) = {
    visited.foldLeft((workQueue, unvisited)) {
      case ((wq, unvis), TypeConstraint.Equality(tpe1, tpe2, _)) =>
        // only include variables
        val f = (t: Type) => if (idMap.getOrElse(t, -1) < 0) findType(t, unvis) else Nil
        val b = (i: List[TypeConstraint], k: List[TypeConstraint]) => i ++ k
        val x = deconstructType(tpe1, f, b, Nil)
        val y = deconstructType(tpe2, f, b, Nil)
        ((x ++ y).foldLeft(wq)((acc, x) => acc.enqueue(x)), unvis.diff(x ++ y))
      case _ => (workQueue, unvisited)
    }
  }


  private def findType(tpe: Type, constr0: List[TypeConstraint]): List[TypeConstraint] = {
    constr0.filter {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isTpe(t: Type, t2: Type): Boolean = t match {
          case Type.Apply(_, _, _) => t.typeArguments.exists(isTpe(_, t2))
          case _ => t == t2
        }

        val a = (x: Boolean, y: Boolean) => x || y
        deconstructType(tpe, isTpe(tpe1, _), a, false) || deconstructType(tpe, isTpe(tpe2, _), a, false)
      case _ => false
    }
  }

  /**
    *
    * @param t       Type
    * @param f       the function to apply to the type
    * @param g       the function to apply in case of a Type.Apply
    * @param default default value to return when fail
    */
  private def deconstructType[A](t: Type, f: Type => A, g: (A, A) => A, default: A): A = t match {
    case Type.Var(_, _) => f(t)
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => f(t)
      case TypeConstructor.Effect(_, _) => f(t)
      case _ => default
    }
    case Type.Apply(tpe1, tpe2, _) => g(deconstructType(tpe1, f, g, default), deconstructType(tpe2, f, g, default))
    case _ => default
  }


  private def constraintToZhegalkin(constr: TypeConstraint, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[(ZhegalkinExpr[CofiniteIntSet], ZhegalkinExpr[CofiniteIntSet])], Map[Type, Int]) = constr match {
    case TypeConstraint.Equality(tpe1, tpe2, _) =>
      typeToZhegalkin(tpe1, idMap) match {
        case (None, nm) => (None, nm)
        case (Some(xh1), nm) => typeToZhegalkin(tpe2, nm) match {
          case (Some(xh2), nnm) => (Some((xh1, xh2)), nnm)
          case (None, nnm) => (None, nnm)
        }
      }
    case _ => (None, idMap)
  }


  private def isDebug(constrs: List[TypeConstraint]): Boolean = {
    constrs.exists {
      case TypeConstraint.Equality(tpe1, tpe2, _) =>
        def isDb(t: Type): Boolean = t match {
          case Type.Cst(tc, _) => tc match {
            case TypeConstructor.Effect(sym, _) => sym match {
              case Symbol.Debug => true
              case _ => false
            }
            case _ => false
          }
          case Type.Apply(tl, tr, _) => isDb(tl) || isDb(tr)
          case _ => false
        }

        isDb(tpe1) || isDb(tpe2)
      case _ => false
    }
  }


  /**
    * convert a Type into a Zhegalkin expression and update the idMap if necessary
    *
    * @param tpe   Type to convert
    * @param idMap map containing ids of converted types
    * @return a tuple of Option[ZhegalkinExpr] and idMap, so an idMap is always returned
    */
  private def typeToZhegalkin(tpe: Type, idMap: Map[Type, Int])(implicit alg: BoolAlg[ZhegalkinExpr[CofiniteIntSet]], scope: RegionScope, renv: RigidityEnv): (Option[ZhegalkinExpr[CofiniteIntSet]], Map[Type, Int]) = {
    val a = (default: Int, z: Int => ZhegalkinExpr[CofiniteIntSet]) => {
      val id = idMap.getOrElse(tpe, default)
      (Some(z(id)), idMap + (tpe -> id))
    }
    val varId = idMap.values.minOption.getOrElse(0).min(0) - 1
    val cstId = idMap.values.maxOption.getOrElse(0).max(0) + 1
    tpe match {
      case Type.Var(sym, _) =>
        if (renv.isFlexible(sym)) {
          a(varId, alg.mkVar)
        }
        else {
          a(cstId, alg.mkCst)
        }
      case Type.Cst(tc, _) => tc match {
        case TypeConstructor.Pure => a(cstId, alg.mkCst)
        case TypeConstructor.Effect(_, _) => a(cstId, alg.mkCst)
        case _ => (None, idMap)
      }
      case Type.Apply(_, _, _) => tpe.baseType match {
        case Type.Cst(tc, _) => tc match {
          case TypeConstructor.Difference =>
            tpe.typeArguments match {
              case left :: right :: _ =>
                typeToZhegalkin(left, idMap) match {
                  case (Some(x), nm) => typeToZhegalkin(right, nm) match {
                    case (Some(y), nnm) => (Some(alg.mkAnd(x, alg.mkNot(y))), nnm)
                    case c => c
                  }
                  case b => b
                }

              case _ => (None, idMap)
            }
          case TypeConstructor.Union =>
            tpe.typeArguments match {
              case left :: right :: _ =>
                typeToZhegalkin(left, idMap) match {
                  case (Some(x), nm) => typeToZhegalkin(right, nm) match {
                    case (Some(y), nnm) => (Some(alg.mkOr(x, y)), nnm)
                    case c => c
                  }
                  case b => b
                }

              case _ => (None, idMap)
            }

          case _ => (None, idMap)

        }
        case _ => (None, idMap)
      }
      case _ => (None, idMap)
    }
  }

  private def isFlexible(tpe: Type)(implicit scope: RegionScope, renv: RigidityEnv): Boolean = tpe match {
    case Type.Var(sym, _) => renv.isFlexible(sym)
    case _ => false
  }

  private def isHandler(tpe: Type): Boolean = tpe match {
    case Type.Apply(tpe1, tpe2, _) => tpe.typeConstructor match {
      case Some(value) => value match {
        case TypeConstructor.Union => isHandler(tpe1) || isHandler(tpe2)
        case TypeConstructor.Intersection => isHandler(tpe1) || isHandler(tpe2)
        case TypeConstructor.Difference => true
        case _ => false
      }
      case None => false
    }
    case _ => false
  }

  private def findHandled(constr: TypeConstraint): Set[Type] = constr match {
    case TypeConstraint.Equality(_, tpe, _) =>
      def a(t: Type): Set[Type] = t match {
      case Type.Apply(tpe1, tpe2, _) => t.typeConstructor match {
        case Some(value) => value match {
          case TypeConstructor.Complement => a(tpe1) ++ a(tpe2)
          case TypeConstructor.Union => a(tpe1) ++ a(tpe2)
          case TypeConstructor.Intersection => a(tpe1) ++ a(tpe2)
          case TypeConstructor.Difference => t.typeArguments match {
            case _ :: rhs :: Nil => consTypeArgs(rhs).toSet
            case _ => Set.empty
          }
          case TypeConstructor.SymmetricDiff => a(tpe1) ++ a(tpe2)
          case _ => Set.empty
        }
        case None => Set.empty
      }
      case _ => Set.empty
    }
      a(tpe)
    case _ => Set.empty
  }

  private def pureSource(typeConstraint: TypeConstraint) = typeConstraint match {
    case TypeConstraint.Equality(_, tpe2, _) => isPure(tpe2)
    case _ => false
  }

  private def typeToSym(tpe: Type): List[EffSymOrRigidVar] = tpe match {
    case Type.Var(sym, _) => List(RigidVar(sym))
    case Type.Cst(tc, _) => tc match {
      case TypeConstructor.Pure => List(Eff(Symbol.mkEffSym("Pure")))
      case TypeConstructor.Effect(sym, _) => List(Eff(sym))
      case TypeConstructor.Union => Nil
      case _ => Nil
    }
    case Type.Apply(tl, tr, _) => typeToSym(tl) ++ typeToSym(tr)
    case _ => Nil
  }
}

